# Generated by Django 4.2.7 on 2023-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sex',
            name='sex',
            field=models.CharField(choices=[('M', 'masculine'), ('F', 'feminine')], max_length=10),
        ),
    ]
